### ISSUE TITLE
This plugin broke normal work of napari

### ISSUE THREAD

**Issue by iyasik** [4DNucleome/PartSeg#891]
**Describe the bug**

When I installed this plugin to napari, napari stopped working properly. I can't open LIF files correctly now as layers or as 3D. Some single channels when selected turn into whole white fields. I used a special environment only for napari. Moreover, I deleted napari, CUDA, tensorflow, conda and re-installed everything again. But this problem persists! I can't use napari at all now... Even the color of napari is still beige and not regularly black. It is very disappointing.
I'm not an expert in programming etc and just want to use napari in my regular image analysis. 
I will appreciate a lot if you can help with how to change everything back to normal and delete the plugin or whatever it changed on my computer.
Thank you 

I run it on Windows10, cuda 11.2, tensorflow-gpu 2.4.2, python 3.8
napari: 0.4.17
Platform: Windows-10-10.0.22000-SP0
Python: 3.8.0 (default, Nov 6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.7
NumPy: 1.24.1
SciPy: 1.10.0
Dask: 2023.1.0
VisPy: 0.11.0
magicgui: 0.6.1
superqt: unknown
in-n-out: 0.1.6
app-model: 0.1.1
npe2: 0.6.2

**Comment by Czaki** [comment]
Hi, 
It looks like the activation of PartSeg changes the theme in napari. 

The bugfix for this problem is already merged to the napari main branch but has yet to be released. 
Since next napari release the settings will be per environment, not a single global one. 
Also, there is work to not blend images with light backgrounds, But I'm not sure when it will be available.

Please open napari. Click from the File menu and select Preferences. Inside the preferences dialog go to Appearance tab and change the napari theme from "light" to "dark".

**Comment by Czaki** [comment]
close because lack of activity
